# Generated by Django 4.0.6 on 2022-08-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('line1', models.TextField(max_length=500)),
                ('line2', models.TextField(max_length=500)),
            ],
        ),
    ]
